services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: P@ssword4
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api: 
    image: vitorlassen/jv3-api-produtos:latest
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:P@ssword4@postgres:5432/postgres
                  # protocolo://usuario  :senha    @servidor:5432/bancodedados

  web: 
    build: . 
    ports: 
      - "5173:5173"
    volumes:
      - .:/app


